//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class corebrain {
  public static int add(int arg0, int arg1) {
    int ret = corebrainPINVOKE.add(arg0, arg1);
    return ret;
  }

  public static string greet(string arg0) {
    string ret = corebrainPINVOKE.greet(arg0);
    return ret;
  }

  public static SWIGTYPE_p_PyMODINIT_FUNC PyInit_corebrain() {
    SWIGTYPE_p_PyMODINIT_FUNC ret = new SWIGTYPE_p_PyMODINIT_FUNC(corebrainPINVOKE.PyInit_corebrain(), true);
    return ret;
  }

}
